### ISSUE TITLE
When try to run the command "domino platform run-compose" occur error info

### ISSUE THREAD

**Issue by wangwei357** [Tauffer-Consulting/domino#201]
demo@demo:~/Desktop/xc$ domino platform run-compose
Traceback (most recent call last):
  File "/home/demo/.local/bin/domino", line 5, in <module>
    from domino.cli.cli import cli
  File "/home/demo/.local/lib/python3.9/site-packages/domino/cli/cli.py", line 7, in <module>
    from domino.cli.utils import pieces_repository, platform
  File "/home/demo/.local/lib/python3.9/site-packages/domino/cli/utils/pieces_repository.py", line 247, in <module>
    def create_compiled_pieces_metadata(source_url: str | None = None) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

The base environment is Python 3.9 ,ubuntu 18.04.6

**Comment by luiztauffer** [comment]
Hi @wangwei357 , this is a Python version error. Please try it in an environment with Python 3.10

**Comment by wangwei357** [comment]
@luiztauffer Thanks for your, I have another question. Can I use win to use this platform？

**Comment by luiztauffer** [comment]
yes, you should be able to run it on windows as well

**Comment by wangwei357** [comment]
@luiztauffer   Sorry to bother you again， when I try deploying this on Win, it occurs other error.....


==============================================
  ____                  _
 |  _ \  ___  _ __ ___ (_)_ __   ___
 | | | |/ _ \| '_ ` _ \| | '_ \ / _ \
 | |_| | (_) | | | | | | | | | | (_) |
 |____/ \___/|_| |_| |_|_|_| |_|\___/

==============================================
Welcome to Domino! ❤️

Traceback (most recent call last):
  File "C:\Users\SZV00594\AppData\Local\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\SZV00594\AppData\Local\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\SZV00594\AppData\Local\anaconda3\Scripts\domino.exe\__main__.py", line 7, in <module>
  File "C:\Users\SZV00594\AppData\Local\anaconda3\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\SZV00594\AppData\Local\anaconda3\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\SZV00594\AppData\Local\anaconda3\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\SZV00594\AppData\Local\anaconda3\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\SZV00594\AppData\Local\anaconda3\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\SZV00594\AppData\Local\anaconda3\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\SZV00594\AppData\Local\anaconda3\lib\site-packages\domino\cli\cli.py", line 214, in cli_run_platform_compose
    platform.run_platform_compose(detached=d, use_config_file=use_config_file, dev=dev)
  File "C:\Users\SZV00594\AppData\Local\anaconda3\lib\site-packages\domino\cli\utils\platform.py", line 663, in run_platform_compose
    subprocess.run(["chmod", "-R", "777", "domino_data"])
  File "C:\Users\SZV00594\AppData\Local\anaconda3\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\SZV00594\AppData\Local\anaconda3\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\SZV00594\AppData\Local\anaconda3\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

The python version is 3.10.12
