### ISSUE TITLE
Workflow run error

### ISSUE THREAD

**Issue by tdari** [Tauffer-Consulting/domino#217]
When I try to run a workflow I get this error. I am using the default workspace. I have tried different workflows but nothing changes.
Running on Docker.
Python 3.10.0 
```
[2024-01-24, 23:30:26 +03] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/domino/custom_operators/docker_operator.py", line 192, in execute
    self._prepare_execute_environment(context=context)
  File "/home/airflow/.local/lib/python3.9/site-packages/domino/custom_operators/docker_operator.py", line 177, in _prepare_execute_environment
    piece_secrets = self._get_piece_secrets()
  File "/home/airflow/.local/lib/python3.9/site-packages/domino/custom_operators/docker_operator.py", line 109, in _get_piece_secrets
    piece_repository_id=piece_repository_data["data"][0]["id"],
KeyError: 'data'
```

**Comment by vinicvaz** [comment]
Hey @tdari thanks for submitting this issue!
You are right, there was a bug in our CD process making the last Domino airflow images running with an outdated version of domino package. Just fixed it, please **remove** all domino images from your docker cache and try to run it again.
Let me know if it worked, you can reopen the issue if no.

Thanks again!

**Comment by tdari** [comment]
Thank you @vinicvaz I cleaned the cache and it works like a charm.

**Comment by vinicvaz** [comment]
@tdari perfect!
Let us know if you find any other bug or if you have any suggestions!
Thanks
